---
build_from:
  amd64: ghcr.io/hassio-addons/debian-base/amd64:6.1.1
  armv7: ghcr.io/hassio-addons/debian-base/armv7:6.1.1
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:6.1.1
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@degatano.com
